### ISSUE TITLE
This plugin is doing too many things

### ISSUE THREAD

**Issue by kflorence** [paulwib/gulp-ssg#12]
The Gulp paradigm is "do one thing and do it well" -- I think all use cases of this plugin are already covered by the following plugins:

- https://github.com/hparra/gulp-rename (generating pretty urls)
- https://github.com/jessaustin/gulp-nav (generating page navigation)

A static site generator is by definition outside the scope of a Gulp plugin -- it should be produced through a combination of gulp plugins.

On a side note, I find the navigation structure of this plugin to be very confusing and found the `gulp-nav` structure to be much more straightforward.

**Comment by paulwib** [comment]
Hopefully the latest version address your concerns - no more built-in file renaming :)
