### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by ChrisSki** [paulwib/gulp-ssg#13]
Hi Paul, this isn't really an issue, so I apologize for leaving this here. Is v2 in good shape to use? The functionality is exactly what I am looking for. I plan on using index.html files, and v2 seems not to care about the extension of the index file.

**Comment by paulwib** [comment]
Hi Chris - it's coming along, should have something released in the next week or so.

**Comment by paulwib** [comment]
Took me a while to get round to it, but first v2 release is done :)
